#!/bin/bash
wget http://uhts-lgtf.vital-it.ch/symlink/ASG8_L4_R1_001_8NyQODXs4lwE.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASG8_L4_R2_001_5FOcXEjxd4ts.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASH5_L5_R1_001_VL9LyvocPVuJ.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASH5_L5_R2_001_5yz1fTUbgtYW.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASS6_L5_R1_001_izAAo1h8Fkh0.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASS6_L5_R2_001_sgfYaLu3R6ti.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONH1_L5_R1_001_4gVWbos0XFTD.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONH1_L5_R2_001_OvoyOJ5bqJRD.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONH7_L4_R1_001_5lTsUABxaFgL.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONH7_L4_R2_001_DyTIeTNRI2l3.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONS4_L5_R1_001_bf0N792CyWSI.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONS4_L5_R2_001_YE1slfSv3KJs.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSK2_L4_R1_001_uWBuCJfOODO1.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSK2_L4_R2_001_rCaJOJKx9ZBC.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSK6_L5_R1_001_k8LMFIcL0jnm.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSK6_L5_R2_001_UiISeSjR6021.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSS5_L4_R1_001_NEHe8KGQwDvs.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSS5_L4_R2_001_8zYujd8S4YWY.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMG4_L5_R1_001_ZTj9HauBRDP4.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMG4_L5_R2_001_yBMwXtt9Wq2C.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMH5_L4_R1_001_ulgKpTtyoCE8.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMH5_L4_R2_001_jE0lYsxZTzOy.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMS3_L4_R1_001_WzFV3jK0ivJK.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMS3_L4_R2_001_R1Kgre22L2jF.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASG6_L5_R1_001_YOyZi6sy9bCw.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASG6_L5_R2_001_gzjkgcDOPoVQ.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASG7_L7_R1_001_dlY7qa1d4DWL.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASG7_L7_R2_001_CkIxY6B8k72d.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASH4_L6_R1_001_fCoyvlKYJWLN.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASH4_L6_R2_001_4Gwxdpu65SW3.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASH6_L8_R1_001_pp6ZcVZcK1gS.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASH6_L8_R2_001_i2HlvzJtwKKi.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASS4_L6_R1_001_88RzzmDlMnUu.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASS4_L6_R2_001_KYHi3UlUwgDI.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASS5_L7_R1_001_xeElfHfoFG2r.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ASS5_L7_R2_001_JQWOXuYvcZrn.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONH3_L7_R1_001_ei2KlICY4nfM.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONH3_L7_R2_001_kpl4zqVs03gN.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONK2_L5_R1_001_wDU2ZrDulD7V.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONK2_L5_R2_001_VYX1Dk0V8o7l.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONK5_L6_R1_001_jUqVIOMeiVBn.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONK5_L6_R2_001_QNlkNcDUKrjT.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONK6_L7_R1_001_6faNUAYmIkFM.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONK6_L7_R2_001_9Yt4r7Tzsxf2.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONS1_L8_R1_001_JehtTafou3Cb.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONS1_L8_R2_001_QpFYcr8zrscP.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONS2_L6_R1_001_8mDcyLhTbF2c.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/ONS2_L6_R2_001_U12HiGBay6OR.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSH3_L8_R1_001_dkgDOgVYev5c.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSH3_L8_R2_001_zFyGWNBUEVtB.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSH4_L5_R1_001_OaPJTV7HUlvJ.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSH4_L5_R2_001_O5wh4hrzbgGi.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSH5_L6_R1_001_qZwAeQvbQsuM.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSH5_L6_R2_001_CB13sIfCNbXF.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSK1_L8_R1_001_bnRnInvaOzlA.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSK1_L8_R2_001_vYG0riGeKsHQ.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSS3_L5_R1_001_SA15u4rPSMpw.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSS3_L5_R2_001_EmH7uQ89GYgg.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSS4_L7_R1_001_529k1U7Bf0z4.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/OSS4_L7_R2_001_IkUuLDKKhCTq.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMG2_L6_R1_001_dECZh7sEf9zu.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMG2_L6_R2_001_rZjPNjwfLTwA.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMG3_L8_R1_001_dh3EmLT5i9jN.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMG3_L8_R2_001_3n0GArTrMF5p.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMH1_L5_R1_001_A2R1ONSBVHza.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMH1_L5_R2_001_E0SofQ4AwAj8.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMH2_L7_R1_001_WM98WsaWEDRe.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMH2_L7_R2_001_hxv1eD5FMInU.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMS1_L5_R1_001_RDN9ow1CizYE.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMS1_L5_R2_001_pgoNf7sOXd4f.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMS2_L8_R1_001_BgPzWYC66Pvw.fastq.gz
wget http://uhts-lgtf.vital-it.ch/symlink/SMS2_L8_R2_001_Ml9rExMP7XIZ.fastq.gz
